nextcloud/collectives

- lib/Fs/UserFolderHelper.php
- tests/Unit/Fs/UserFolderHelperTest.php
If the admin does it it's expected they know what they're doing and the mount point should work.
> Add app config to specify default app folder location

- .github/workflows/cypress.yml
- .weblate
- Makefile
- README.md
> Remove references to weblate

- .github/workflows/cypress.yml
- cypress/e2e/pages.spec.js
- package-lock.json
- package.json
In GitLab by @raudius on Aug 4, 2022, 17:43
Signed-off-by: Raul <r.ferreira.fuentes@gmail.com>
> Reenable cypress search test

- src/components/PageList/Item.vue
> Fix vertical center alignment of page list icons

- renovate.json
> Configure renovate bot

- cypress.config.js
- package-lock.json
- package.json
- renovate.json
> More NPM updates

- README.md
- lib/Service/PageService.php
- tests/Unit/Service/PageServiceTest.php
> Ignore attachments folder when deleting/renaming pages

- Makefile
> Makefile: Minor fixes and improvements to release target

- .github/workflows/app-upgrade-mysql.yml
- .github/workflows/cypress.yml
> Checkout 'main' branch of Text if we run against server master

- lib/Service/PageService.php
> Remove obsolete verifySubpageOrder code

- lib/Service/PageService.php
- src/components/Collective.vue
- tests/Unit/Service/PageServiceTest.php
- tests/psalm-baseline.xml
Ensures that page list is refreshed on each relevant change.
At the same time makes sure it's only refreshed on page list changes, not on other filesystem changes.
Fixes: #441
> Use custom notify_push message to update page list

- src/components/Collective/CollectiveActions.vue
> Use MDI icon for collective settings action

- src/components/Page/PageInfoBar.vue
- src/components/Page/TextEditor.vue
> Fix sticky text menubar

- CHANGELOG.md
- Makefile
- appinfo/info.xml
- src/store/pages.js
> Prepare for 2.3.0 release

- src/components/Member/MemberPicker.vue
> l10n: Fixed grammar

- src/components/PageList/Item.vue
> Use Collectives icon for landing page if collective has no emoji set

- src/components/Page.vue
> Reset outline showing state when switching between pages

- .github/workflows/behat-sqlite-encryption.yml
- docs/content/administration/_index.md
- lib/Mount/CollectiveMountPoint.php
- lib/Mount/CollectiveStorage.php
- tests/stub.phpstub
> Support server side encryption in CollectiveStorage

- .github/workflows/behat-sqlite-encryption.yml
- .github/workflows/behat-sqlite.yml
- lib/Service/CircleHelper.php
- lib/Service/CollectiveService.php
- tests/Integration/features/bootstrap/FeatureContext.php
- tests/Integration/features/collective.feature
- tests/psalm-baseline.xml
- tests/stub.phpstub
> Flag circles for collectives as managed by app

- src/components/Member/MemberSearchResult.vue
- src/components/Page/PagePicker.vue
- src/components/PageList.vue
- src/components/PageList/Item.vue
Explanation: the color-primary variables are not to be used in components because the introduce problems with high-contrast primary colors. Fix this by using the primary-element variables instead.
> Use the color-primary-element* variables

- cypress/e2e/pages-links.spec.js
- src/components/Page/RichText.vue
> Fix relative paths to pages from landing page

- DEVELOPING.md
- package.json
- src/files.js
- src/reference.js
- src/shared-init.js
- webpack.js
> Add `npm run serve` and update development docs

- src/views/CollectiveView.vue
> Lower minimum page list width to 15%

- lib/Search/CollectiveProvider.php
- lib/Search/PageContentProvider.php
- lib/Search/PageProvider.php
> fix(backend): remove duplicate `/` from links to app in search providers

- lib/Search/CollectiveProvider.php
- lib/Search/PageContentProvider.php
- lib/Search/PageProvider.php
See https://github.com/nextcloud/collectives/pull/763#pullrequestreview-1519024441
> fix(search): generate absolute links, fixes previews from smart picker

- src/components/Collective.vue
- src/components/Navigation.vue
- src/components/Page.vue
- src/components/Page/RichText.vue
- src/components/Page/TextEditor.vue
- src/components/PageList.vue
- src/components/SkeletonLoading.vue
- src/mixins/pageMixin.js
- src/store/circles.js
- src/store/pages.js
> feat: add component SkeletonLoading

- composer.lock
- tests/stub.phpstub
Auto-generated update of [nextcloud/ocp](https://github.com/nextcloud-deps/ocp/) dependency
> [main] Update nextcloud/ocp dependency

- .github/workflows/cypress.yml
This ensures that each spec is run for each server version.
- this commit fixes our test setup - no additional tests needed
- no docs needed.
> test(ci): group cypress tests by server version

- CHANGELOG.md
- appinfo/info.xml
- docs/content/administration/_index.md
> feat(release): prepare for 2.7.1 release

- .github/workflows/lint-eslint.yml
- .github/workflows/lint-stylelint.yml
- .github/workflows/node.yml
- .github/workflows/pr-feedback.yml
- .github/workflows/update-nextcloud-ocp-matrix.yml
In particular this will avoid downloading cypress when not needed and make the affected runs more stable against network timeouts and failures.
- Tests are improved by this
- Documentation is not required
> ci: Update workflows from templates

- .github/workflows/cypress.yml
Right now i need this to see if exceptions in failed runs also occure in successful runs.
> test(ci): always upload nextcloud log for debugging

- .github/workflows/cypress.yml
The occ commands trigger circles requests which only succeed if the server is running.
In the `nextcloud.log` after current CI runs - in particular with server from the current main branch there are a number of `OCA\\Circles\\Tools\\Exceptions\\RequestNetworkException` resulting from occ commands.
<details>
<summary>Exception logged</summary>
```json
{
"Exception": "OCA\\Circles\\Tools\\Exceptions\\RequestNetworkException",
"Message": "",
"Code": 0,
"Trace": [
{
"file": "/home/runner/work/collectives/collectives/apps/circles/lib/Service/FederatedEventService.php",
"line": 443,
"function": "doRequest",
"class": "OCA\\Circles\\Service\\FederatedEventService",
"type": "->",
"args": [
[
"OCA\\Circles\\Tools\\Model\\NCRequest"
]
]
},
{
"file": …
```
> test(ci): Start the php server before adding users and groups

- cypress/e2e/settings.spec.js
- cypress/runLocal.sh
This should fix the cypress settings tests on stable25 and stable26.
> fix(cypress): Always open new folder in file picker

- .github/workflows/app-upgrade-mysql.yml
- .github/workflows/behat-sqlite-encryption.yml
- .github/workflows/behat-sqlite.yml
- .github/workflows/cypress.yml
- .github/workflows/occ-cli-mysql.yml
- .github/workflows/phpunit-sqlite.yml
Nextcloud master will soon require PHP 8.1 at least.
> test(ci): Bump PHP version to 8.2 in most cases

- CHANGELOG.md
- appinfo/info.xml
> feat(release): Prepare for 2.8.0 release

- CHANGELOG.md
- appinfo/info.xml
> Prepare 2.8.1 release

- .github/workflows/app-upgrade-mysql.yml
Let's see if we can reproduce the update failure to 2.8.1
> test(update): run app update test with mysql 8.0

- .github/workflows/app-upgrade-postgres.yml
> test(ci): Test app upgrade on postgresql

- appinfo/info.xml
- lib/Db/CollectiveUserSettings.php
- lib/Migration/Version000003Date20200720000000.php
- lib/Migration/Version000200Date20200822000000.php
- lib/Migration/Version000400Date20210324000000.php
- lib/Migration/Version000500Date20210421000000.php
- lib/Migration/Version001600Date20211025000000.php
- lib/Migration/Version002000Date20220103000000.php
- lib/Migration/Version002000Date20220210000000.php
- lib/Migration/Version010200Date20220616000000.php
- lib/Migration/Version010300Date20220623000000.php
- lib/Migration/Version020100Date20221111000000.php
- lib/Migration/Version020600Date20230412160400.php
- lib/Migration/Version020600Date20230519000000.php
- lib/Migration/Version020802Date20231004000000.php
- psalm.xml
JSON as DB field type causes too much headache, let's do the JSON parsing in PHP instead.
Fixes: #917
> fix(db): make settings field from collectives_user_settings type string

- lib/Controller/PublicStartController.php
- src/components/Collective/CollectiveActions.vue
* Don't show `Leave collective` in public share
* Don't show footer in public shares
Fixes: #848
Fixes: #944
> Public share fixes

- .github/workflows/behat-sqlite.yml
- .github/workflows/lint-php.yml
To be prepared for the bump with Nextcloud 28
> chore(php): Add PHP 8.3 to test matrix

- .github/workflows/behat-sqlite-encryption.yml
- package-lock.json
Fixes several security vulnerabilities.
> fix(deps): Update NPM dependencies

- docs/content/administration/_index.md
- docs/content/usage/_index.md
See https://help.nextcloud.com/t/searching-in-collectives/116551/6 for more info
Thought it was worth having this in the docs.
> Add information on searching collectives

- src/components/Collective.vue
- src/css/editor.scss
> fix(Collective): Fix alignment of page heading skeleton

- lib/Dashboard/RecentPagesWidget.php
- lib/Model/RecentPage.php
- lib/Service/RecentPagesService.php
Fixes: #1010
:derelict_house:  Before | 🏡 After
|---|---
> fix(dashboard): Display parent page path in recent pages widget

- src/components/Page.vue
- src/components/Page/TextEditor.vue
- src/mixins/editorMixin.js
Only do so in edit mode.
Fixes: #989
> fix(page): Save document on <Ctrl>-<S> when page title is focussed

- lib/Dashboard/RecentPagesWidget.php
Adds the icon URL to the dashboard widget so that it can be used by clients that don't support the icon class.
> feat(dashboard): Add icon URL

- lib/AppInfo/Application.php
- lib/Team/CollectiveTeamResourceProvider.php
- tests/psalm-baseline.xml
Requires https://github.com/nextcloud/server/pull/43855
> feat: Implement a team resource provider

- lib/Controller/PublicPageController.php
- lib/Service/PageService.php
> fix(pages): Set correct `filePath` for shares of subpages

- lib/AppInfo/Application.php
- lib/SetupChecks/CirclesAppIsEnableCheck.php
- lib/SetupChecks/PDOSQLiteDriverIsEnableCheck.php
- psalm.xml
* Resolves: https://github.com/nextcloud/collectives/issues/1031
> Add setup checks for sqlite driver & circles app

- docs/content/administration/_index.md
> docs: Add documentation about using `group_everyone` app

- src/components/PageList/Item.vue
> fix(draggable): `draggable` attribute to HTML elements requires `true`

- src/components/Member/MemberPicker.vue
- src/components/Page/LandingPageWidgets/MembersWidget.vue
- src/components/Page/LandingPageWidgets/RecentPagesWidget.vue
- src/mixins/editorMixin.js
This fixes "Error: Debounced method called with different contexts." errors.
> fix(debounce): Register debounced functions in instance context

- appinfo/routes.php
- lib/Controller/PageController.php
- src/apis/collectives/pages.js
- src/apis/collectives/urls.js
- src/components/PageList.vue
> add content search to collectives

- src/components/Page/LandingPageWidgets/MembersWidget.vue
> fix(MembersWidget): Resize according to available space

- src/components/PageList.vue
> fix(PageList): Reset content filtered pages when switching collectives

- src/components/Page/LandingPageWidgets/RecentPagesWidget.vue
> fix(recentPages): Allow toggleing in public share

- composer.json
- composer.lock
> chore(deps): Update composer dependencies to stable27 baseline

- src/Collectives.vue
- src/components/Collective.vue
- src/components/Member/Hint.vue
- src/components/Member/Member.vue
- src/components/Nav/CollectiveSettings.vue
- src/components/Nav/CollectivesTrash.vue
- src/components/Nav/NewCollectiveModal.vue
- src/components/Page.vue
- src/components/Page/EditButton.vue
- src/components/Page/LandingPageWidgets/MembersWidget.vue
- src/components/Page/LandingPageWidgets/RecentPageTile.vue
- src/components/Page/PageActionLastUser.vue
- src/components/Page/PageInfoBar.vue
- src/components/Page/PagePicker.vue
- src/components/Page/TextEditor.vue
- src/components/Page/Version.vue
- src/components/PageList.vue
- src/components/PageList/Item.vue
- src/components/PageList/PageTrash.vue
- src/components/PagePrint.vue
- src/components/PageSidebar.vue
- src/components/PageSidebar/SharingEntryLink.vue
- src/components/SkeletonLoading.vue
- src/css/editor.scss
- src/views/CollectiveView.vue
* Resolves: #1359 
---|---
B | A
> Adjust styling to not break with Nextcloud 30 design

- .github/workflows/cypress-e2e.yml
- cypress.config.js
- package-lock.json
- package.json
> ci(cypress): Use cypress-split for running tests in parallel

- lib/Controller/CollectiveController.php
- lib/Controller/CollectiveUserSettingsController.php
- lib/Controller/PageController.php
- lib/Controller/PageTrashController.php
- lib/Controller/PublicCollectiveController.php
- lib/Controller/PublicPageController.php
- lib/Controller/PublicPageTrashController.php
- lib/Controller/PublicStartController.php
- lib/Controller/SessionController.php
- lib/Controller/SettingsController.php
- lib/Controller/ShareController.php
- lib/Controller/StartController.php
- lib/Controller/TrashController.php
> controller: Migrate to attributes and add rate limits for public pages

- lib/Controller/ShareController.php
- lib/Service/CollectiveShareService.php
- src/components/PageSidebar/SharingEntryLink.vue
> fix(share): Fix updating shares with empty password, feedback on error

- cypress/e2e/collective-share.spec.js
- cypress/e2e/page-list.spec.js
- cypress/e2e/page-share.spec.js
- src/Collectives.vue
- src/components/Collective.vue
- src/components/Member/Member.vue
- src/components/Member/MemberPicker.vue
- src/components/Member/SelectedMembers.vue
- src/components/Nav/CollectiveMembersModal.vue
- src/components/Nav/CollectiveSettings.vue
- src/components/Nav/CollectivesGlobalSettings.vue
- src/components/Nav/CollectivesTrash.vue
- src/components/Nav/NewCollectiveModal.vue
- src/components/Page.vue
- src/components/Page/LandingPageWidgets.vue
- src/components/Page/LandingPageWidgets/RecentPagesWidget.vue
- src/components/Page/PageActionMenu.vue
- src/components/Page/PageInfoBar.vue
- src/components/Page/PagePicker.vue
- src/components/Page/TextEditor.vue
- src/components/Page/Version.vue
- src/components/PageList/Item.vue
- src/components/PageList/PageTrash.vue
- src/components/PagePrint.vue
- src/components/PageSidebar/SharingEntryLink.vue
- src/components/PageSidebar/SidebarTabAttachments.vue
- src/mixins/pageMixin.js
* Resolves: #1397 
---|---
---|---
---|---
---|---
--- | ---
---|---
---|---
---|---
---|---
--- | ---
> Address Nextcloud 30 design review comments

- src/Collectives.vue
- src/components/CollectivePrint.vue
Fixes isPublic detection in Text editor on public shares.
> fix(shares): Provide hidden element `isPublic` on public shares.

- CHANGELOG.md
- appinfo/info.xml
> chore(release): Prepare for 2.14.0 release

- src/components/Page.vue
- src/components/Page/Version.vue
> fix(titlebar): bring back top padding on Nextcloud < 30

- CHANGELOG.md
- appinfo/info.xml
> chore(release): Prepare 2.14.1 release

- lib/Service/PageService.php
> fix(PageService): Always pass a bool to `fromFile()` for `fullWidth`

- src/components/PageList/Draggable.vue
- src/components/PageList/Item.vue
- src/mixins/pageMixin.js
> fix(PageList): Fix moving page by drag and drop

- package-lock.json
> fix(deps): npm audit fix

- src/components/Nav/CollectiveSettings.vue
- src/stores/collectives.js
> fix(CollectiveSettings): Rename collective

- package-lock.json
- package.json
- src/components/PageList.vue
Fixes: #1339
---|---
| Screencast |
| --- | 
| ![recording1](https://github.com/user-attachments/assets/35635d35-2f9b-4ef5-b34a-6963626a5290) |
> fix(PageList): Calculate scroller height dynamically for filtered view

- lib/AppInfo/Application.php
- lib/Db/Collective.php
- lib/Mount/MountProvider.php
- tests/Integration/config/behat.yml
- tests/Integration/features/bootstrap/FeatureContext.php
- tests/Integration/features/mountpoint.feature
> fix(mount): public shares always get permissions of a simple user

- lib/Dashboard/RecentPagesWidget.php
* Resolves: https://github.com/nextcloud/collectives/issues/1475
---|---
> Use the dark svg for widget icon

- Makefile
> fix(Makefile): Run distclean as dependency of release

- src/components/PageList.vue
> fix(PageList): Add icon to clear the filter/search string

- .github/CODEOWNERS
Changing code owners to apply to all code paths
> chore: Update code owners according to maintenance responsibilities

- src/components/PageList.vue
- src/components/PageList/PageTrash.vue
> fix(PageList): Make header, landing page and trash sticky again

- src/components/PageList/PageFavorites.vue
> fix(favorites): Show details when clicking on a favorite

- lib/Service/PageService.php
- tests/Unit/Service/PageServiceTest.php
> fix(PageService): Fix page link for index pages

- .github/workflows/cypress-e2e.yml
- CHANGELOG.md
- appinfo/info.xml
> chore(release): Prepare 2.15.2 release

- tests/Integration/features/bootstrap/FeatureContext.php
Should fix CI after server changes
> tests(integration): Fix login by setting origin header

- cypress/support/commands.js
This is replication of https://github.com/nextcloud/text/pull/6819 to Collectives repository in order to fix Cypress tests
> ci: Hotfix to make login work as long as we are on older cypress version

- CHANGELOG.md
- appinfo/info.xml
* ✨ Add Nextcloud 31 support
* ✅ Adjust tests to Nextcloud 31 login changes
* 💽 Make collectives work with sharding
* 🗣️ Translation updates from Transifex. Thanks to all contributors.
* ⬆️ Update NPM dependencies.
* ⬆️ Update PHP composer dependencies.
> Prepare 2.16.0 release

- src/stores/pages.js
Fixes jumping page order when adding a new page.
> fix(store): add missing `newPageId` getter

- cypress/e2e/page-landingpage.spec.js
- src/css/editor.scss
Also add a test to prevent further regressions.
Fixes: #1704
---|---
> fix(page): Scroll container for the page content

- cypress/e2e/page-landingpage.spec.js
- src/components/Page/PageInfoBar.vue
- src/css/editor.scss
> fix(editor): Amend the scroll container tests and adjust menubar padding

- CHANGELOG.md
- appinfo/info.xml
> chore(release): Prepare for 2.16.2 release

- src/components/PageList/Item.vue
Fixes a regression from last release.
> fix(PageList): Fix expanding/collapsing pages with subpages

- CHANGELOG.md
- appinfo/info.xml
> chore(release): Prepare 2.16.3 release

- src/components/Page.vue
- src/components/Page/PageInfoBar.vue
- src/components/Page/PageTitleBar.vue
- src/components/Page/TextEditor.vue
- src/css/editor.scss
> fix(landingpage): Make toolbar sticky to bottom on mobile

- cypress/e2e/page-anchor-links.spec.js
- cypress/e2e/pages.spec.js
- src/components/Page.vue
- src/components/Page/TextEditor.vue
- src/mixins/editorMixin.js
> fix: Scroll to location hash when opening an anchor link

- CHANGELOG.md
- appinfo/info.xml
- lib/Migration/MigrateTemplates.php
> fix(upgrade): Use local `putContent` function in MigrateTemplates

- cypress/e2e/page-list.spec.js
- lib/Db/Collective.php
- src/components/PageList.vue
- src/stores/pages.js
- src/stores/templates.js
- src/tests/util/sortOrders.spec.js
- src/util/sortOrders.js
Fixes: #1680
| 🏡 After |
|--- |
| ![image](https://github.com/user-attachments/assets/04753cd9-fa8d-4d57-9e0a-0755cd53dbb5) |
| Screencast |
| --- |
| ![recording1](https://github.com/user-attachments/assets/9e245059-2b08-4bb9-9897-4c60bac5fafe) |
> feat(PageList): Allow to sort pages descending by title/time

- src/components/Collective.vue
- src/stores/sessions.js
Random finding while working on the OCS API refactoring.
> fix(session): Fix session calls from frontend

- lib/Dashboard/RecentPagesWidget.php
> fix(RecentPagesWidget): Fix link to route

- lib/Versions/VersionsBackend.php
Fixes: #1860
See https://github.com/nextcloud/server/pull/53833 .
> fix(api): Add getRevision function required by NC 32

- src/components/Collective.vue
> fix(session): Only initialize a collective session as logged in user

- CHANGELOG.md
- lib/Service/RecentPagesService.php
- src/components/Collective.vue
- src/components/Page/LandingPageWidgets/RecentPageTile.vue
> fix(RecentPage): Fix landing page detection

- CHANGELOG.md
- appinfo/info.xml
> chor(release): Prepare 3.0.3 release

- src/components/Page/TagsModal.vue
> fix(TagsModal): Don't show a toast when not tags got deleted

- src/components/PageList/Item.vue
> fix(PageList): fix color of favorite star on Nextcloud 32

- src/composables/useEditor.js
Wait for the editor to be created so we can destroy it
if the component is unmounted before the editor loaded.
This avoids a race condition
when NcAppContent rendered the default template twice.
> fix(editor): always delete editor

- CHANGELOG.md
- appinfo/info.xml
> chore(release): prepare 3.2.0 release
