lib/Controller/StartController.php, lib/Events/CollectivesLoadAdditionalScriptsEvent.php, src/components/Collective/CollectiveActions.vue
Other apps can listen to CollectivesLoadAdditionalScriptsEvent to load additional JS scripts when the Collectives app is rendered.
If they define an object OCA.Collectives.CollectiveExtraAction with string `title` and callback function `click`.
=> Add API to register extra collective action for other apps

cypress/e2e/collective.spec.js, lib/Listeners/BeforeTemplateRenderedListener.php, package-lock.json, package.json, src/files.js, src/helpers/files.js, src/views/FileListInfo.vue
Inside collectives folders in the Files app, display an info box and a button to navigate to the Collectives app instead.
Fixes: #138
* Resolves: #138
=> Display info with a link to Collectives in Files app

src/components/Collective/CollectiveActions.vue, src/components/Page/PageActionMenu.vue
The actions depend on currentCollective, which is only available in PageAction context, not in the collectives list.
Fixes: #475
=> Only display collective extra action in landing page actions

.github/workflows/behat-sqlite.yml, .github/workflows/cypress.yml
Speed up CI a bit. Let's see how the numbers are since collectives has quite a good coverage :)
=> ci: Use apcu and speed up basic auth for cypress/integration tests

.github/workflows/app-upgrade-mysql.yml, .github/workflows/behat-sqlite.yml, .github/workflows/lint-eslint.yml, .github/workflows/occ-cli-mysql.yml, .github/workflows/phpunit-sqlite.yml, cypress/e2e/pages.spec.js, src/components/Page/MoveModal.vue, src/components/Page/PageActionMenu.vue, src/components/Page/PagePicker.vue, src/mixins/pageMixin.js, src/store/pages.js
Allows to move pages between subpages and in sort order inside
Fixes: #462
Action | Modal
---|---
[recording.webm](https://user-images.githubusercontent.com/3582805/210185543-c6491c9b-2f42-4976-9eca-842829edab7f.webm)
=> Add modal to move pages inside the collective

lib/Model/PageInfo.php, lib/Mount/CollectiveFolderManager.php, lib/Service/PageService.php, tests/Unit/Model/PageInfoTest.php, tests/Unit/Service/PageServiceTest.php
In GitLab by @juliushaertl on Aug 18, 2022, 13:28
- Build parent node name from path without getting the parent node 
- Pass parent node where available to avoid extra db queries
- Cache root storage id per request to avoid duplicate queries
Cuts down the queries in half on our perftesting instance for the handbook example collective: 948 -> 541
Related upstream fix in server, but is not fully applicable here due to the recursive directory iteration https://github.com/nextcloud/server/pull/33602
Fixes #377
=> Build parent path without queries

cypress/e2e/pages.spec.js, src/components/CollectiveNotFound.vue
=> Fix title and description of EmptyContent in CollectiveNotFound

src/components/Collective/CollectiveActions.vue
With https://github.com/nextcloud/circles/pull/1236 leaving will fail if the user is not a direct member. This change will make sure the explanation is shown to the user.
=> Improve error message when leaving a collective fails

DEVELOPING.md
Installed collectives today in a fresh ubuntu 20.04 and it was missing these.
=> Mention required php extensions in DEVELOPING

src/components/CollectivePrint.vue
added collective name to the document title before printing.
* Resolves: #474
=> fix:collective name gets added in printview

src/components/Page.vue, src/components/Page/EditButton.vue, src/components/Page/RichText.vue, src/components/Page/TextEditor.vue
Preparations for using the new editor API from Text, see https://github.com/nextcloud/text/pull/3615
=> Refactor: Move TextEditor handling in its own component

src/views/FileListInfo.vue
This shrinks the collectives-files.js asset from 4MB to ~100KB.
=> Import nc-vue component separately in FileListInfo component

cypress/e2e/pages.spec.js
* Fixes CI failures such as https://github.com/nextcloud/collectives/actions/runs/4103191125/jobs/7077067180
(Please note that the retries fail for a different reason)
=> fix(cypress): selector for mention autocompletion

lib/ACL/ACLStorageWrapper.php, lib/ACL/ACLStorageWrapper25.php, lib/ACL/ACLStorageWrapper26.php, lib/Mount/CollectiveFolderManager.php, psalm.xml, tests/Unit/ACL/ACLStorageWrapperTest.php
Changed in https://github.com/nextcloud/server/pull/36120
Should still be compatible with 25 as adding the return type on the child class is ok if none is there on the parent.
=> fix: Adapt return type for Nextcloud 26

lib/ACL/ACLStorageWrapper.php
Otherwise the inheriting classes cannot call it.
Fixes #549.
=> fix(ACL): Make checkPermissions protected.

.github/dependabot.yml, .github/workflows/cypress.yml
Update engines workflow to v2 to prevent node 12 deprecation warnings.
And let Dependabot update the workflows.
=> Update engines workflow for prevent deprecation warnings

lib/Service/CollectiveHelper.php
Instead of getting the circle power level by re-querying each circle from the database, simply reuse the circle we already have
this saves having to query N circles when getting collectives for user
=> Reuse the circle we already have to get the level for the user

src/views/CollectivePrintView.vue
Currently an additional page is printed because of the height setting of the body tag,
this is fixed by setting the body height to fit the content.
See page number(s):
---|---
=> fix: Prevent empty additional pages added when printing

cypress/e2e/collective-readonly.spec.js, src/components/Page.vue, src/components/Page/PageActionMenu.vue
* Don't load emoji picker if collective is readonly
* Show stripped-down page actions menu in readonly mode
* Resolves: #559
=> Readonly view fixes in page titlebar

src/components/Nav/NewCollective.vue
* Resolves: #548 
This resolves some styling issues, like hovering the submit input does not set the border on the text input or mismatching borders. Moreover the `NcMultiselect` is deprecated and should be replaced with the `NcSelect`.
---|---
. | ![submit button with correct borders](https://user-images.githubusercontent.com/1855448/218200555-ec9318a5-7278-4e07-973d-dc4e3bda3209.png)
Please note that the missing primary color border on hover will be fixed with the next vue components update (see https://github.com/nextcloud/nextcloud-vue/pull/3701 )
=> Fix `new collective` name input elements

.github/workflows/cypress.yml, cypress/Dockerfile, cypress/docker-compose.yml, cypress/e2e/pages.spec.js, cypress/entrypoint.sh, cypress/runLocal.sh, lib/AppInfo/Application.php, lib/Listeners/CollectivesReferenceListener.php, lib/Reference/PageReferenceProvider.php, lib/Reference/SearchablePageReferenceProvider.php, lib/Search/CollectiveProvider.php, lib/Search/PageProvider.php, lib/Service/CollectiveService.php, lib/Service/PageService.php, package-lock.json, package.json, src/reference.js, src/views/PageReferenceWidget.vue, tests/Unit/Service/CollectiveServiceTest.php, tests/psalm-baseline.xml, webpack.js
closes #509 
Hey how. Here is a reference provider using the existing search provider.
It comes with a basic reference widget.
Not sure about the `PageReferenceProvider::resolveReference` implementation which might be a bit brutal but I didn't find a simpler way to get the page and the collective entities.
Also not sure about the widget content. Feel free to completely change it.
I took the liberty to display the emojis in the search results which I find nicer but that's just a suggestion. Feel free to get rid of this.
One more doubt: I didn't find an easy way to resolve the link without the file ID (when the fileId GET param is not there). Should we make it possible to resolve without the page file ID?
=> Add reference provider and basic reference widget

cypress/e2e/pages-links.spec.js, cypress/e2e/pages.spec.js, cypress/support/commands.js
Make sure that the search part of URLs matches the expected value.
=> Cypress: Refactor link handling tests

cypress/e2e/pages-links.spec.js, src/components/Page/RichText.vue
* Make sure `handleRelativeFileLink` doesn't fail if the search params of `href` don't contain a fileId param.
* Treat links with absolute and relative paths to local collective the same as links with full URLs with origin.
* Attempt to resolve links to relative paths to markdown files
Fixes: #385
=> Improve link handling

src/components/Collective/CollectiveActions.vue, src/components/Nav/CollectiveSettings.vue, src/components/Page/PageActionMenu.vue, src/components/PageList.vue, src/components/PageSidebar/SidebarTabBacklinks.vue, src/components/PageSidebar/SidebarTabVersions.vue, src/store/pages.js
* Migrate SidebarTabVersions to NcListItem
* Migrate SidebarTabBackLinks to NcListItem
* Migrate share icons to vue-material-design-icons
* Migrate name field in CollectiveSettings for NcTextField component
* Resolves: #608
* Resolves: #389
=> Migrate to nextcloud-vue components in sidebar and CollectiveSettings

lib/Service/PageService.php
* Resolves: #655
Avoid errors when the user cannot be found and additionally makes use of the display name cache which might save some queries
=> fix: Use getDisplayName to avoid calling on null

cypress/e2e/page-details.spec.js, cypress/e2e/page-list.spec.js, cypress/e2e/pages.spec.js, cypress/support/commands.js
Cypress pages test was taking way longer than all the others. Split out:
* Page details spec: test rendering of details about one page.
* Page list spec: test rendering lists of pages.
=> cypress: split up page test some

src/components/Nav/CollectiveListItem.vue, src/store/collectives.js
=> Fix path to collective in navigation of public share

src/components/Page/PageActionMenu.vue
I corrected a simple bug where a letter 's' was missing from the section name in the string `t('collective', 'Select emoji')`
=> Fix localization section for select emoji

appinfo/routes.php, lib/Controller/StartController.php
This is required to have a trailing slash in our default route (`collectives.start.index`).
Fixes: #727
Fixes: #411
=> Add extra default route without path parameter

lib/Mount/CollectiveStorage.php
Adapt to the rename of the internal scanner class for object storage. I kept the NoopScanner to not break compatibility with old releases. 
This originates from https://github.com/nextcloud/server/pull/37691 so it would be good to include it in the next bugfix release for 27 as well.
=> fix: Switch to ObjectStoreScanner if NoopScanner is not available

cypress/e2e/pages.spec.js
=> fix(cypress): Fix flaky tests from `pages.spec.js` on stable25

src/components/Page/TextEditor.vue
Together with https://github.com/nextcloud/text/pull/4540, the cursor position will be restored when opening the editor for a page.
=> fix(editor): Use the `autofocus` command from Text if available

lib/Versions/CollectiveVersionsExpireManager.php
Required to unbreak `CollectiveVersionsExpireManager` with latest Nextcloud 28.
Fixes: #710
=> fix(backend): Use IDispatcher instead of Symfony EventDispatcher

cypress/e2e/page-landingpage.spec.js, src/components/LastUserBubble.vue, src/components/Member/CurrentMembers.vue, src/components/Member/Member.vue, src/components/Member/MemberPicker.vue, src/components/Nav/CollectiveMembersModal.vue, src/components/Page.vue, src/components/Page/LandingPageWidgets.vue, src/components/Page/LandingPageWidgets/MembersWidget.vue, src/components/Page/LandingPageWidgets/RecentPageTile.vue, src/components/Page/LandingPageWidgets/RecentPagesWidget.vue, src/components/Page/LandingPageWidgets/WidgetHeading.vue, src/components/Page/PageInfoBar.vue, src/components/Page/TextEditor.vue, src/components/SkeletonLoading.vue, src/store/circles.js, src/store/pages.js
* Show 10 most recent pages on landing page.
* Show 3 last active members on landing page if it's not a public share.
* Resolves: #311
| Overview |
|---|
| ![grafik](https://github.com/nextcloud/collectives/assets/3582805/3885eb23-fabb-43f2-beaa-5fd2bffe71bf) |
| Screencast (slightly outdated) |
|---|
| [recording1.webm](https://github.com/nextcloud/collectives/assets/3582805/7da61f0e-0954-4300-99fe-e9a0447f8dea) |
=> List recent pages and members on landing page

cypress/support/commands.js, src/main.js
Required for loading webpack chunks if the app is in a non-default apps folder (like `apps-extra/`).
=> fix(webpack): set `__webpack_public_path__`

src/Collectives.vue, src/components/Page.vue, src/components/Page/Editor.vue
As https://github.com/nextcloud/text/pull/2832 introduced a max-height to properly handle `.text-editor` being the scroll container for any viewer rendered editor, we will need to adapt the styling here slightly as collectives comes with its own scroll container.
Note that the API for rendering the editor externally would solve that as this one doesn't bring its own scroll container https://github.com/nextcloud/text#%EF%B8%8F-integrate-text-in-your-app but needs more work to have feature parity for collectives.
=> fix: Make sure collectives own scroll area is used for menubar stickyness

src/main.js, src/shared-init.js
Otherwise mermaid diagrams are not loaded in read only view as the async chunks cannot be fetched due to CSP errors
=> fix: Use shared init file to properly set nonce for async component loading

cypress/e2e/apps.spec.js, cypress/e2e/collective.spec.js, cypress/e2e/settings.spec.js
* Resolves: https://github.com/nextcloud/collectives/actions/runs/5981758520/job/16230201814
---|---
| A
=> fix(cy): use flexible selector for file list in Nextcloud 25-28

.github/workflows/cypress.yml
=> ci(cypress): Test against stable27

lib/Mount/CollectiveFolderManager.php, lib/Mount/LazyFolder.php, lib/Trash/PageTrashBackend.php, tests/Integration/features/pagesDisabledTrashAndVersion.feature
Required because constructor parameters changed for the private LazyFolder class with Nextcloud 28.
=> fix(CollectiveFolderManager): Use our own LazyFolder implementation

.github/workflows/phpunit-sqlite.yml, lib/Versions/CollectiveVersionsExpireManager.php, tests/Unit/BackgroundJob/CollectiveVersionsExpireManagerTest.php
Fix https://github.com/nextcloud/collectives/issues/828
=> fix: Fallback to old eventdispatcher on older releases

src/components/Page/LandingPageWidgets/RecentPagesWidget.vue
Seems like recent upstream CSS changes introduced a margin for buttons. See screenshot.
---|---
=> fix(RecentPagesWidget): Remove margin of slider button

.github/workflows/cypress.yml
We reached the limit of free test runs in the Cypress cloud, so let's disable parallelization via Cypress cloud for now.
=> ci(cypress): disable parallelization via Cypress cloud

lib/Search/PageContentProvider.php, tests/Unit/Search/PageContentProviderTest.php
When a result is found in the index
but the corresponding file does not exist in the storage anymore skip the result and return the other search results.
Fixes #873.
- no docs needed as this is a bugfix.
=> fix(search): handle removed files gracefully

.github/workflows/cypress.yml
Use different names for the artifacts so they all become available.
Also rename the screenshot artifacts
to clearify which version they are for.
=> test(ci): upload all the nextcloud logs in cypress tests

.github/workflows/cypress.yml
Let's not add to the tracked CI runs in the cypress cloud while we cannot see them.
=> churn(ci): stop recording runs while we cannot see the results

src/Collectives.vue, src/components/Collective.vue, src/components/Page/LandingPageWidgets/RecentPageTile.vue
=> Fix visual glitches

cypress/e2e/collective.spec.js, lib/Listeners/BeforeTemplateRenderedListener.php, src/files/FilesCollectiveHeader.js, src/helpers/files.js, src/init.js, webpack.js
* Resolves: #860
- Documentation is not required
=> Bring back file list header in Nextcloud 28

lib/Trash/PageTrashBackend.php
=> fix(PageTrashBackend): Ignore emty relativePath in `getTrashNodeById()`

cypress/e2e/collective-settings.spec.js, cypress/e2e/pages.spec.js, lib/Db/Collective.php, lib/Db/Page.php, lib/Service/CollectiveService.php, lib/Service/PageService.php, src/components/Icon/CollectivesIcon.vue, src/components/Icon/PageIcon.vue, src/components/Icon/PageTemplateIcon.vue, src/components/Icon/PagesTemplateIcon.vue, src/components/Nav/CollectiveSettings.vue, src/components/Page.vue
Fixes: #422
Requires https://github.com/nextcloud-libraries/nextcloud-vue/pull/4575
=> fix(EmojiPicker): allow to unselect collective and page emoji

lib/Migration/Version020800Date20230911000000.php
Otherwise: `Not null violation: 7 ERREUR:  la colonne « settings » contient des valeurs NULL`
=> fix(migrations): set default value for new not null column

.github/workflows/cypress.yml
The matrix syntax to enable this is somewhat hard to parse.
In case of a PR the matrix will contain one entry for use-cypress-cloud
with the value `true`. Otherwise it will have one entry `false`.
This way we can exclude containers for the case without the cypress cloud.
=> test(cypress): record PRs and run them in parallel

.github/workflows/cypress.yml
Cypress is currently failing on the main branch with:
```
You passed the --ci-build-id, --group, --tag, --parallel, or --auto-cancel-after-failures flag without also passing the --record flag.
The --ci-build-id flag you passed was: Cypress - 2f6588277fb008bc1e918726f469df2e01e50d1d
These flags can only be used when recording to Cypress Cloud.
```
Frankly... I have no idea why as i thought all these options were blank when not using cypress cloud.
So this is an attempt at fixings this.
The `ci-build-id` is not in our yml file and will only be passed if either `parallel` or `group` are given.
https://github.com/cypress-io/github-action/blob/bd9dda317ed2d4fbffc808ba6cdcd27823b2a13b/index.js#L667-L680
So I suspect we're still passing group.
=> test(ci): do not use group parameter when run without cypress cloud

lib/Service/PageService.php
=> fix(PageService): preg_quote `trusted_domains` before using in regexp

cypress/e2e/pages.spec.js
=> test(cy): unified search now uses a button not an a

.github/workflows/cypress.yml
Luckily cypress handles this pretty well and only the first runner per version will actually run the tests. But still 8 minutes of CI time just for setting up test runners that do nothing.
Only one runner per version as the var is not set.
=> test(ci): only use cypress cloud if var is set in github

src/components/Page/PageActionMenu.vue
Apparently `/apps/files/?fileId=<id>` no longer works. Let's use `/f/<id>` instead.
=> fix(PageActionMenu): Fix link to file in files app on Nextcloud 28

src/components/Page.vue, src/components/Page/Editor.vue, src/components/Page/LandingPageWidgets.vue, src/components/Page/PageInfoBar.vue, src/components/Page/TextEditor.vue, src/components/Page/Version.vue, src/components/SkeletonLoading.vue, src/css/editor.scss
Otherwise we break the layout of Text in Viewer (e.g. when opening a linked file in the viewer).
---|---
=> fix(editor): Set CSS variable `--text-editor-max-width` per default

src/Collectives.vue, src/components/Collective/CollectiveActions.vue, src/components/CollectivePrint.vue, src/components/Page/LandingPageWidgets.vue, src/components/Page/RichText.vue, src/components/Page/TextEditor.vue, src/components/PageList/Item.vue, src/components/PagePrint.vue
* Provide "Export or print" action on readonly collectives
* Fix link to print view on public shares
* Don't print landing page widgets
* Get rid of empty trailing page when printing
* Fix detection of images in print view
* Don't cut pages on Firefox
* Get rid of background and border when printing
---
* Fixes: #542 
* Fixes: #543
* Replaces: #544
=> Printing fixes

composer.json
Our dependency tntsearch requires it.
Fixes psalm and php lint CI workflows with PHP 8.2
=> fix(composer): Add dependency on `php-pdo_sqlite`

appinfo/info.xml
This reverts commit ded9ccef908be28b9f9567f162495ba16035cf42.
Unfortunately Nextcloud chokes on either `ext-pdo` or `pdo` as lib dependencies:
* https://github.com/nextcloud/collectives/actions/runs/6782002055/job/18433356004?pr=936#step:11:269
* https://github.com/nextcloud/collectives/actions/runs/6782055403/job/18433521697?pr=936#step:11:269
=> Revert "chore(info.xml): Add `ext-pdo` and `ext-pdo_sqlite` as lib dependencies"

.github/ISSUE_TEMPLATE/Bug_report.md
https://github.com/nextcloud/text/pull/4261 improved the text issue template but that change wasn't copied here. The updated template is more specific on what it wants be filled out and simplifies the overall process.
=> chore: Update issue template

cypress/e2e/dashboard-widget.spec.js, cypress/support/commands.js, lib/AppInfo/Application.php, lib/Dashboard/RecentPagesWidget.php, lib/Model/RecentPage.php, lib/Service/CollectiveHelper.php, lib/Service/CollectiveService.php, lib/Service/RecentPagesService.php, tests/psalm-baseline.xml
Fixes: #113 
The implementation is not necessarily the most performant one… but using the services of Collectives that already are at hand.
=> enh(dashboard): add recent pages dashboard widget

cypress/e2e/collective.spec.js, src/components/Member/MemberPicker.vue, src/components/Member/MemberSearchResults.vue, src/components/Member/SelectedMembers.vue, src/components/Nav/NewCollectiveModal.vue
People got confused by searching their own user.
---|---
=> fix(NewCollectiveModal): Mention that own user is part of collective

lib/Service/PageService.php, tests/Unit/Service/PageServiceTest.php
For example, the smart picker inserts links in this format.
Fixes: #1007
=> fix(backlinks): Accept `<link>` syntax as valid in parsed markdown

src/views/FileListInfo.vue
This fixes the info header being always displayed for guest users.
* Fixes: #893
* Fixes: #863
=> fix(FileListInfo): Don't show info header if collectivesFolder is `/`

lib/Dashboard/RecentPagesWidget.php
The widget didn't respect the limit. This limit can be specified in the dashboard API so it is important to follow it.
=> fix(dasbhoard): Respect item limit

CHANGELOG.md
* Resolves: most of the changelog content being "stricken through"
There was a markdown formatting issue.
=> docs(changelog): correct styling removing unwanted strike-through

src/constants.js, src/mixins/editorMixin.js, src/store/store.js
Only do this if editor API is version 1.1 or newer to not break usage with older Text versions.
This builds on nextcloud/text#5042.
Fixes: #620 
Fixes: #964
=> feat(editor): Pass fileId to editor API for reader

cypress/e2e/circle-with-group.spec.js, cypress/e2e/collective-members.spec.js, cypress/e2e/collective-page-mode.spec.js, cypress/e2e/collective-readonly.spec.js, cypress/e2e/collective-settings.spec.js, cypress/e2e/collective-share.spec.js, cypress/e2e/collective.spec.js, cypress/e2e/collectives-trash.spec.js, cypress/e2e/dashboard-widget.spec.js, cypress/e2e/page-details.spec.js, cypress/e2e/page-landingpage.spec.js, cypress/e2e/page-list.spec.js, cypress/e2e/page-share.spec.js, cypress/e2e/pages-links.spec.js, cypress/e2e/pages.spec.js, cypress/e2e/settings.spec.js, cypress/support/commands.js, cypress/support/navigation.js, src/apis/collectives/collectives.js, src/apis/collectives/index.js, src/apis/collectives/pages.js, src/apis/collectives/settings.js, src/apis/collectives/shares.js, src/apis/collectives/urls.js, src/apis/collectives/userSettings.js, src/store/collectives.js, src/store/pages.js, src/store/settings.js
Wrap all usage of the collectives api in a simple functional interface.
This will allow us to change the layout of the api
and only update it in a single place.
Separate the API handling from the store.
The api is concerned with axios and generateUrl
while the store is only concerned with the current state of the app.
Accept multiple arguments to `collectivesUrl` and `pagesUrl`
and join them with `/` to build the url:
Example:
```js
api.pagesUrl({collectiveId: 10}, 'trash', 12)
```
results in `/apps/collectives/_api/10/_pages/trash/12`
Use the api directly in the cypress commands.
That way we do not require the page to be loaded.
Also extract `collective-edit-mode.spec.js` from `pages.spec.js`.
It requires a different beforeEach function
to seed the edit mode before visiting the …
=> Javascript wrapper for collectives API

.github/workflows/pages.yml
Required by upload/artifacts v4.
Failed run:
https://github.com/nextcloud/collectives/actions/runs/7321770406/job/19942569756
=> Build(deps): Bump actions/upload-pages-artifact from 2 to 4

.github/workflows/pages.yml
v4 does not even exist.
I was confusing `actions/artifact@v4` and `actions/upload-pages-artifact`.
=> Chore(ci): fix pages workflow with upload-pages-artifacts@v3

.github/workflows/renovate-approve-merge.yml
Approve all renovate PRs and set them to automerge.
This way they will be merged as soon as CI passes.
=> churn(ci): automerge renovate prs

lib/Listeners/BeforeTemplateRenderedListener.php, tests/stub.phpstub
Signed-off-by: Julius Härtl <jus@bitgrid.net>
Make sure that unrelated pages do not load the editor as we don't need it there.
To reproduce open an unrelated page and see editor scripts as well as the reference provider scripts loaded though not needed e.g. https://nextcloud.local/index.php/s/ for a 404 page
=> fix: Do not load editor on unrelated pages

.gitignore
When running php-cs-fixer locally the file is created, but it wasn't ignored until now.
=> chore: Add PHP-CS-Fixer cache to .gitignore

cypress/e2e/pages-links.spec.js, cypress/support/commands.js, lib/Mount/LazyFolder.php, lib/Reference/SearchablePageReferenceProvider.php, lib/Service/PageService.php, src/main.js, src/views/PageReferenceWidget.vue
Starting with Nextcloud 29, clicking on a link opens the link bubble. This bubble contains a preview, clicking on it opens the link. It's no longer possible to pass a custom link handler into the Text app. Instead, all custom link handling needs to happen in the custom reference providers that provide the link preview.
Also starting with Nextcloud 29, all links to the collectives app open in the same tab, regardless whether in edit or view mode.
=> Fix link handling with new link bubble from Nextcloud 29

lib/Search/FileSearch/FileSearcher.php, lib/Service/SearchService.php
This change improves morphology in search functionality by providing correct Stemmer for TNTSearch
---|---
=> Set default language for TNTSearch

src/components/PageList.vue
Remove `menuName` property to make it an icon-only button.
---|---
=> fix(PageList): Fix sort menu button

lib/Reference/SearchablePageReferenceProvider.php
=> fix(ReferenceProvider): Check `pathinfo` return value before using it

src/Collectives.vue, src/mixins/editorMixin.js
Steps to reproduce:
- Create long page with multiple headings
- Click on heading in the bottom of the page
- Copy url from address bar with anchor and open it in new tab
Expected result:
- Content scrolled to heading
Actual result:
- There are no scroll
---|---
=> Fix anchcors scrolling

DEVELOPING.md, docs/content/administration/_index.md
=> docs: Remove app store link for shipped apps and mention both circles/teams

lib/Trash/CollectivePageTrashItem.php
NC major 30 and above require a deletedby parameter for the Trashitem constructor. For now we should pass null to make collectives work again/ let CI be green again.
=> adapt collectives for NC 30

src/components/Nav/CollectivesTrash.vue
* Resolves: #1250 
The button text is not readable, so this PR aligns the buttons in a column layout instead, and moves the "Cancel" button to the bottom.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> Make permanently delete collective buttons readable

cypress/e2e/collective-share.spec.js, cypress/e2e/page-list.spec.js, cypress/e2e/pages.spec.js, cypress/support/commands.js
`cy.type()` requires a typable element. `cy.getEditor()` returns the wrapper which is not writable, so use `cy.getEditorContent(true)` to get the contenteditable element.
=> test(cypress): Fix typing into editor

src/components/LastUserBubble.vue, src/mixins/editorMixin.js
Revert "fix(editor): start immediately in debounced updateEditorContent function"
This reverts commit ab651d87b0a2eb0852f701da3fd866e254f8eaa7.
Fixes: #1194
=> Revert `immediate: true` in debounced `updateEditorContent()`

src/components/Nav/CollectivesTrash.vue
=> chore(CollectivesTrash): Replace `»«` quotes with `""`

cypress/e2e/collective.spec.js, cypress/e2e/settings.spec.js, src/views/Home.vue
=> fix: Automatically open collective if only one exists

lib/Db/CollectiveMapper.php
`array_filter()` returns an array with out-of-order keys when removing elements that are not the last one from an indexed array. This results in `json_encode()` returning an associative array, which is interpreted as dict by the javascript frontend.
Fixes: #1289
=> fix(CollectiveMapper): Always return trashed collectives as simple list

lib/Service/PageService.php, src/components/LastUserBubble.vue
* fix(LastUserBubble): Fix displaying user bubble
* fix(PageService): Don't update last edit user with subpageOrder
* Resolves: #1122
=> Last edit user related fixes

lib/Reference/SearchablePageReferenceProvider.php
Found while looking through sentry errors:
[PHP] Undefined array key "fileId" at /var/www/nextcloud/apps/collectives/lib/Reference/SearchablePageReferenceProvider.php#87
=> fix: Properly check for fileId parameter

lib/Fs/UserFolderHelper.php
When a file from a collective is shared to another user the mountpoint we are running into some frequent invalidation of the mount point cache. 
Steps to reproduce
1. admin and user1 have different languages
1. Have a collective that two users admin and user1 are part of
2. Share a file from this collective from from user1 to admin
3. Access the files list as admin, see that the path of the mountpoint that is requested for user1 actually uses the Collective folder name from admin (which is different due to the other language)
We basically reuse the collective user folder name from the first mount point in https://github.com/nextcloud/collectives/blob/1c7d1956cee227b2c1fa8df248249d3874927449/lib/Mount/MountProvider.php#L49-L59
=> fix: Avoid reusing the collectives user folder for different users

cypress/e2e/settings.spec.js
Should fix the flaky collectives folder setting test.
=> test(cypress): Wait until empty folder is loaded in settings test

lib/Service/PageService.php, src/util/displayError.js
Also contains a small formatting fix when displaying error messages from the backend in the frontend.
=> Don't show an error in frontend if files_trashbin is disabled

.github/ISSUE_TEMPLATE/Bug_report.md, .github/workflows/behat-sqlite-encryption.yml, .github/workflows/behat-sqlite.yml, .github/workflows/phpunit-sqlite.yml, .github/workflows/update-nextcloud-ocp-matrix.yml, appinfo/info.xml, cypress/e2e/collective-share.spec.js, cypress/e2e/page-details.spec.js, cypress/e2e/pages-links.spec.js, cypress/e2e/pages.spec.js, cypress/support/commands.js
`.github/ISSUE_TEMPLATE/Bug_report.md` was migrated from DOS to Unix line breaks, that's why the diff shows the whole file being rewritten.
=> chore: Drop Nextcloud 26 support (no longer supported)

src/components/Page.vue, src/components/PageList.vue, src/components/SearchDialog.vue, src/mixins/editorMixin.js, src/store/search.js, src/store/store.js
* Resolves: #648 
This pull request integrates search highlighting from the text app into collectives.
https://github.com/user-attachments/assets/c8614202-f057-464f-94ed-de05b38249ef
=> feat: Search highlighting for Collectives

lib/Service/PageService.php, tests/Unit/Service/PageServiceTest.php
I'm cleaning up some local stashed changes, opening a PR to not forget about this one, still needs proper testing and performance measurements
This one targets optimizing the initial page load on `PageController::index` (currently quite slow with P95 of 5.80s on our instance) where a list of all pages are loaded. The current logic:
- get index file (checks for a file that we could reuse the results from the getDirectoryListing to obtain it)
- check if folder has subpages (calls getDirectoryListing)
- get directory content (calls getDirectoryListing again)
New logic would be to only get the directory listing once and reuse it for other checks
=> perf: Optimize getPagesFromFolder to avoid requests for files that already get obtained through directory listing

appinfo/routes.php, cypress/e2e/pages.spec.js, lib/Controller/PageController.php, lib/Db/Page.php, lib/Migration/Version021200Date20240725154232.php, lib/Model/PageInfo.php, lib/Service/PageService.php, package-lock.json, package.json, src/apis/collectives/pages.js, src/components/Page.vue, src/components/Page/PageActionMenu.vue, src/components/Page/Version.vue, src/stores/pages.js, tests/Integration/features/bootstrap/FeatureContext.php, tests/Integration/features/pages.feature
Currently we are storing "Full width" inside local storage. This means, that this setting not shares between users and browsers. Would be nice to make this setting persistent on db level like in Confluence.
https://github.com/user-attachments/assets/8b7372fe-807c-4a69-8db3-6d359a76ac0b
=> Save full width of page on server

src/components/Navigation.vue
Also put the button into an `li` element.
Fixes: #1382
---|---
=> fix(Navigation): use `NcAppNavigationNew` for new button

lib/Service/PageService.php
=> fix(PageService): Don't run `getFullWidth()` on null page

lib/Search/FileSearch/FileIndexer.php
=> fix(FileIndexer): Don't choke on missing files

src/mixins/editorMixin.js, src/mixins/pageContentMixin.js
* fix(editor): Pass onCreate callback to editor API - Makes sure that reader content is updated with editor content on initial load.
* fix(pageContent): Add cache buster param to DAV request - Ensures that we always get the latest DAV content and nobody (neither browser nor server) cache anything in between.
Fixes: #1437
=> fixes to display latest page content in reader

src/tests/util/sortOrders.spec.js, src/util/sortOrders.js
=> fix(PageList): Sort numbers numeric (2 > 10)

lib/Service/PageService.php, tests/Unit/Service/PageServiceTest.php
This fixes detecting preview links, as they have `preview` set as title in the markdown link syntax.
Fixes: #1451
=> fix(backlinks): Detect links with title in markdown syntax

src/components/Nav/CollectiveListItem.vue
This also results in the page list being reloaded.
Fixes: #1233
=> fix(Navigation): Show details when switching collective on mobile

templates/error.php
=> fix(error): Improve design of missing app error box

src/components/SearchDialog.vue
This PR changes the positioning of the search dialog so that it doesn't float up depending on the length of the page content. For pages with very little content, e.g. one word, it would float up; now, it will always stick to the bottom of the page.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> fix: search dialog stick to bottom of page

src/components/Collective.vue, src/components/Page/PageInfoBar.vue, src/components/Page/TextEditor.vue, src/components/SearchDialog.vue, src/css/editor.scss
This fixes stickyness of the search dialog to the bottom with long documents.
We have 2 or 3 elements in `app-content-details`: the page title, the editor, and optionally the search dialog. Page title and editor should align to the top, search dialog shall align to the bottom. Scroll container shall be in the editor.
First, the editor didn't take all space, so with a short document, the search dialog didn't align to the bottom. This was tried to fix by e9180858f5545883149e91e90ca76245a33a0958, which had other unwanted side effects. So another attempt was bfb69b3fa1c0556e9e10fa1801fb1fe65dcebd54. But the scroll container was wrong, so the search dialog moved out of the viewport with this approach. Instead of playing around more with `position: sticky` I decided to migrate it to `flexbox` …
=> fix(css): Use flexbox to align editor container and search dialog

lib/Mount/CollectiveStorage.php
=> fix(CollectiveStorage): adjust `getOwner` to NC31

src/components/Collective.vue, src/components/Page/PageInfoBar.vue, src/css/editor.scss
* Complementary PR to nextcloud/text#6404
=> fix(editor): Add bottom border to menubar

src/components/Member/Member.vue, src/components/Member/MemberPicker.vue
=> fix(member): close actions menu when scrolling members

lib/Service/PageService.php
* fix(PageService): Create landing page if missing
* fix(PageService): Ignore folders if parent folder has no index page
* Fixes: #943
* Fixes: #1494
=> fix(PageService): Handle errors with missing index files

.github/dependabot.yml, src/components/Nav/NewCollectiveModal.vue
=> fix(NewCollective): Use display name of own user instead of user ID

lib/Controller/SettingsController.php, lib/Mount/MountProvider.php, src/components/Nav/CollectivesGlobalSettings.vue, tests/Integration/features/bootstrap/FeatureContext.php, tests/Integration/features/mountpoint.feature, tests/Unit/Controller/SettingsControllerTest.php
=> fix: Allow to mount the collectives user folder into a subfolder

Makefile
`ifeq (, $(wildcard $(BUILD_TOOLS_DIR)/composer.phar))`
is evaluated before any targets are build.
Therefore the file still exists.
It is only removed later when the `dist-clean` target is build.
Use a file prerequisit instead.
This is evaluated when the target is build.
---|---
=> fix(Makefile): evaluate composer prerequisits during build

.github/workflows/behat-sqlite-encryption.yml, .github/workflows/behat-sqlite.yml, lib/ACL/ACLStorageWrapper.php
=> chore: Add return types of storage wrapper

Makefile
=> chore(build): Exclude rector.php when building the release tarball

.github/workflows/behat-sqlite-encryption.yml, .github/workflows/behat-sqlite.yml, composer.json, composer.lock, lib/AppInfo/Application.php, lib/Controller/PageTrashController.php, lib/SetupChecks/CirclesAppIsEnableCheck.php, lib/SetupChecks/PDOSQLiteDriverIsEnableCheck.php, vendor-bin/behat/composer.lock, vendor-bin/cs-fixer/composer.lock, vendor-bin/phpunit/composer.lock, vendor-bin/psalm/composer.lock
Only needed for psalm checks, which got moved to its own vendor-bin environment.
This reverts commit df190af3720be2073aaa80a5868a853733dbf3ba.
=> fix(deps): Remove dev dependency on nextcloud/ocp

appinfo/routes.php, cypress/e2e/page-list.spec.js, lib/Controller/CollectiveUserSettingsController.php, lib/Db/Collective.php, lib/Db/CollectiveUserSettings.php, lib/Service/CollectiveHelper.php, lib/Service/CollectiveUserSettingsService.php, src/apis/collectives/userSettings.js, src/components/Page/PageActionMenu.vue, src/components/PageList.vue, src/components/PageList/Item.vue, src/components/PageList/PageFavorites.vue, src/components/PageList/SubpageList.vue, src/stores/collectives.js, src/stores/pages.js, tests/Integration/features/bootstrap/FeatureContext.php, tests/Integration/features/userSettings.feature, tests/Unit/Db/CollectiveUserSettingsTest.php, tests/Unit/Service/CollectiveServiceTest.php, tests/Unit/Service/CollectiveUserSettingsServiceTest.php
Allow to mark pages as favorites. Favorites will get additionally listed in a collapsible "Favorites" section at the top of the page list.
Resolves: #300 
No Favorites | Favorites expanded | Favorites collapsed | Favorites actions
---|--- | --- | ---
| Screencast |
| --- |
| ![recording1](https://github.com/user-attachments/assets/fe6df584-bcca-4450-860f-dc6887061d9f) |
=> Favorite pages

lib/Db/Collective.php
=> fix(share): Add owner sharing permission for folder of public share

src/components/Page/LandingPageWidgets.vue, src/components/Page/TextEditor.vue, src/css/editor.scss
=> fix: Alignment of landing page widgets

lib/Service/RecentPagesService.php, tests/Unit/Service/RecentPagesServiceTest.php
Signed-off-by: Julius Knorr <jus@bitgrid.net>
Fix #1538
=> perf(dashboard): Use storage id for more performant index usage on dashboard query

src/components/Page/TextEditor.vue, src/constants.js, src/mixins/editorMixin.js, src/stores/root.js
* Requires https://github.com/nextcloud/text/pull/6560
* Fixes: #1371
* Fixes: #1322
=> fix(PageInfoBar): Update timestamp when page gets saved via "Done" button

src/Collectives.vue, src/components/Page/TextEditor.vue, src/components/PagePrint.vue, src/components/SearchDialog.vue, src/css/editor.scss
* Fixed alignment of narrow page content
* No cropped page content on the right side
* No page break between page title and content when printing single page
* Print page content after first page when printing single page
=> fix(css): Several print style fixes

src/mixins/editorMixin.js
This is still required for link handling in Nextcloud 27 and 28.
=> fix(editor): Restore accidently removed editor API `onLinkClick` callback

src/mixins/editorMixin.js
Should make it easier to debug sync issues.
| Screenshot |
| --- |
| ![2024-11-04T16:30:16,061786243+01:00](https://github.com/user-attachments/assets/4070f082-50d2-47ab-98a5-bd956c174150) |
=> feat: Expose debug function via OCA.Collectives

lib/Service/PageService.php, tests/Unit/Service/PageServiceTest.php
Fixes the scenario where a folder is missing the index page but one of its subfolders contains pages.
=> fix(PageService): Create index page if folder or subfolders have pages

src/components/Page.vue, src/components/Page/TextEditor.vue, src/components/SearchDialog.vue, src/css/editor.scss
* Resolves: #1577
* Resolves: #1578
Tested:
```
fix(css): New scroll container to fix page design
* Page title always sticky at the top
* Landing page widgets (optional) and page content in scroll container
* Search bar (if visible) always sticky at bottom
Also give the editor some minimum scroll height so that it's possible to
scroll down when the landing page widgets cover full page height (e.g.
on small mobile screens) and the page has no/short content.
```
```
fix(css): Fix maximum editor/page width on mobile
Maximum width should be the smaller value of either text editor width or
screen width.
```
=> Further CSS fixes

lib/Service/CircleHelper.php, lib/Service/CollectiveHelper.php, tests/stub.phpstub
`probeCircles()` is lighter and more performant.
Fixes: #498
Requires https://github.com/nextcloud/circles/pull/1758
=> fix(circles): Use `probeCircles()` instead of `getCircles()`

cypress/e2e/page-details.spec.js, cypress/e2e/pages.spec.js, src/components/Page/TextEditor.vue, src/css/editor.scss
Fixes: #1614
| 🏡 After |
| ---|
| ![recording1](https://github.com/user-attachments/assets/50310aa7-bf52-44b9-be40-887c0b6e5177) |
=> fix(editor): Position outline in the margin left of editor

lib/Mount/CollectiveFolderManager.php
Fix https://github.com/nextcloud/collectives/issues/1619
Based on https://github.com/nextcloud/groupfolders/pull/3483
For queries to the filecache we need to provide the sharding key (storage id) so the sharding logic in server can put the query to the right shard. https://github.com/nextcloud/collectives/pull/1630/files#diff-070d4f3f410c3f2fe7c8c4ab40af4884d62b754f28350d2bb0ebc4fc3f846117R208 is the most relevant change
CI run in https://github.com/nextcloud/collectives/pull/1634
Failure shown in [nextcloud/collectives/actions/runs/12777873556/job/35619586742?pr=1634](https://github.com/nextcloud/collectives/actions/runs/12777873556/job/35619586742?pr=1634)
=> fix: hint table for columns for sharded queries

appinfo/info.xml
Preparing for https://github.com/nextcloud/collectives/issues/1628
CI already is running against master, so no surprises expected.
=> chore: Bump max-version to 31

Makefile
The previous pattern did not exclude files that had multiple dots
like `.Makefile.swp`.
Fixes #1648 .
=> fix(build): exclude all hidden files and folders

lib/Service/RecentPagesService.php
The query turns out to be quite slow as the order by statement will cause the wrong index to be used which leads to long query times on larger filecache tables.
I only consider this a workaround, as changing the query like this will not catch pages that are only in the filecache and do not have an entry in the collectives table, but this is an acceptable tradeoff I think.
---
```
ANALYZE SELECT `p`.*, `f`.`mtime` as `timestamp`, `f`.`name` as `filename`, `f`.`path` as `path` FROM `oc_filecache` `f` LEFT JOIN `oc_collectives_pages` `p` ON `f`.`fileid` = `p`.`file_id` WHERE (`f`.`storage` = '2') AND (`f`.`path` LIKE 'appdata_ocmk9xspynvl/collectives/12/%') AND (`f`.`mimetype` = 1
4) ORDER BY timestamp limit 7;
+------+-------------+-------+--------+------------------------------------------- …
```
=> perf(dashboard): Optimize query to fetch recent pages

.github/workflows/cypress-e2e.yml, .github/workflows/dependabot-approve-merge.yml, .github/workflows/lint-eslint.yml, .github/workflows/lint-info-xml.yml, .github/workflows/lint-php-cs.yml, .github/workflows/lint-php.yml, .github/workflows/lint-stylelint.yml, .github/workflows/node.yml, .github/workflows/pages.yml, .github/workflows/phpunit-sqlite.yml, .github/workflows/pr-feedback.yml, .github/workflows/psalm.yml, .github/workflows/renovate-approve-merge.yml, .github/workflows/reuse.yml, lib/Controller/PublicCollectiveController.php, lib/Controller/PublicPageController.php, lib/Controller/PublicPageTrashController.php, lib/Controller/PublicStartController.php, lib/Db/Page.php, lib/Mount/CollectiveStorage.php, lib/Team/CollectiveTeamResourceProvider.php, psalm.xml, tests/psalm-baseline.xml, tests/stub.phpstub
- Adapting https://github.com/nextcloud/text/commit/64d9887bf94c7d23d9f8094b427ba03b5fbfd4ce to make cypress pass again
- Update action templates
- Pin actions to hashes
- Fix psalm
=> Fix CI and update github actions

src/components/PageList/SubpageList.vue
=> fix: use half icon size for subpage indention

renovate.json
Vueuse 12 dropped Vue 2 support.
=> ci(renovate): pin vueuse to version 11 until we migrate to vue3

src/components/Page/LandingPageWidgets.vue, src/components/Page/TextEditor.vue, src/css/editor.scss
The heading "landing page" caused confusion, took unnecessary space and made the layout even more complex.
---|---
=> fix(landingpage): replace editor heading with a thin line

src/components/Page/LandingPageWidgets/RecentPagesWidget.vue
Fixes the sliding button style on hover/focus.
---|---
=> fix(landingpage): sliding buttons style

composer.json, lib/Service/CircleHelper.php
In our organization we have circles with thousands of people. This leads api for fetching collectives list extremely slow, up to 30s. This happens because we loading all members of the circle for canLeave check. With suggested change we can reduce amount of loaded users
---|---
B | A
=> Optimize collectives fetching

src/components/PageList/Item.vue
Also fixes scrolling the active page into viewport when it's a favored page.
Fixes: #1673
=> fix(PageList): Scroll favored page in page list into viewport

src/components/Page/LandingPageWidgets.vue
Do not show the Team Overview button on public share
=> fix(landingpage): Do not show the Team Overview button on public share

appinfo/routes.php, cypress/e2e/page-landingpage.spec.js, lib/Controller/CollectiveUserSettingsController.php, lib/Db/Collective.php, lib/Db/CollectiveUserSettings.php, lib/Service/CollectiveHelper.php, lib/Service/CollectiveUserSettingsService.php, src/apis/collectives/userSettings.js, src/components/Page/LandingPageWidgets.vue, src/components/Page/LandingPageWidgets/MembersWidget.vue, src/components/Page/LandingPageWidgets/RecentPageTile.vue, src/components/Page/LandingPageWidgets/RecentPagesWidget.vue, src/components/Page/LandingPageWidgets/WidgetHeading.vue, src/stores/collectives.js, tests/Unit/Db/CollectiveUserSettingsTest.php, tests/Unit/Service/CollectiveServiceTest.php
* fix(LandingPage): Hide recent pages widget if less than four pages
* fix(LandingPageWidgets): Show team overview button only with >1 member
* fix(MembersWidget): Use clearer icons for the members list button
* refactor(LandingPage): Move team overview button into MembersWidget.vue
* feat(LandingPage): Add members widget caption and allow to toggle visibility
* fix(WidgetHeading): Use smaller font size and main text color
* fix(RecentPages): Use more condensed layout for tiles
* Fixes: #1698
* Fixes: #1745
---|---
=> fix(LandingPage): Several landing page widgets improvements

.github/workflows/cypress-e2e.yml, cypress/e2e/page-mentions.spec.js, lib/AppInfo/Application.php, lib/Listeners/TextMentionListener.php, tests/stub.phpstub
Requires https://github.com/nextcloud/text/pull/6923
Fixes https://github.com/nextcloud/collectives/issues/1469
This makes sure that for mentions in collectives we have a proper notification message and redirect the user to the collective page instead of the file.
=> feat: Implement a custom notification message for mentions

lib/Service/PageService.php, src/mixins/pageMixin.js, src/stores/pages.js, tests/Unit/Service/PageServiceTest.php
* Page order was jumping in UI when a new page got created (frontend)
* Page order of pages with subpages was broken after creating a new subpage of their parent
* Resolves: #1360
=> Page list sorting fixes

lib/Db/CollectiveMapper.php, lib/Db/CollectiveShareMapper.php, lib/Db/CollectiveUserSettingsMapper.php, lib/Db/PageMapper.php
Fixes "Calling OCP\DB\QueryBuilder\IQueryBuilder::andX without parameters is deprecated and will throw soon."
=> fix(CollectiveMapper): Don't call `andX()` without parameters

.github/workflows/psalm-migrations.yml
We had upgrade failures already a few times in the past because a migration or repair step referenced a new constant or function in an existing class.
Due to the way app upgrades are handled in Nextcloud, the same PHP process that patches the app sources with the new ones from the app store then runs the new migrations and repair steps. Existing classes don't get refreshed before that, so depending on new objects in an existing PHP class can cause problems here.
This commit adds a CI check that statically checks the migrations and repair steps from latest development branch along with the app code of the former app store release.
This should catch situations where we accidentally depend on new objects in migrations.
=> test(ci): Run psalm against app store release with latest migrations

src/components/PageList.vue, src/components/PageList/Draggable.vue
This amends #1808. With the former fix, every dragarea had a bottom padding, i.e. also the one from subpage lists.
=> fix(PageList): Add bottom padding only to dragarea of top-level page list

.github/workflows/app-upgrade-mysql.yml, .github/workflows/app-upgrade-postgres.yml, .github/workflows/cypress-e2e.yml, .github/workflows/psalm-migrations.yml
* Use current hour to only cache it for maximum one hour
=> fix(ci): Cache appstore repository in Github workflow

.github/workflows/lint-php-cs.yml, .github/workflows/phpunit-sqlite.yml
Include changes from https://github.com/nextcloud/.github/pull/538
"Do not update dependencies in vendor-bin when removing nextcloud/ocp".
* Found when investigating #1821 failure.
=> fix(ci): bump php workflows

lib/Command/GenerateSlugs.php, lib/Migration/GenerateSlugs.php
There might be cruft collectives in the database where the cirlce is missing. We have a CircleDestroyedListener that removes the collective alongside with the circle. But there's still corner cases. E.g. the Collectives app might have been disabled while a circle got destroyed.
=> fix(GenerateSlugs): Catch error when circle is missing

cypress/e2e/page-details.spec.js, src/components/Page/EditButton.vue, src/components/Page/PageActionMenu.vue, src/components/Page/PageTitleBar.vue, src/components/Page/SearchDialog.vue, src/components/Page/TextEditor.vue, src/components/PageSidebar/SidebarTabAttachments.vue, src/mixins/editorMixin.js, src/stores/circles.js, src/stores/collectives.js, src/stores/pages.js, src/stores/root.js, src/stores/settings.js, src/stores/shares.js, src/stores/templates.js
Use `useLocalStorage` composable from vueuse to persist parts of the pinia store state.
=> Persist parts of pinia store in browser localStorage

CHANGELOG.md, src/apis/collectives/collectives.js, src/apis/collectives/sessions.js
=> fix(api): Fix URL to delete a session

src/mixins/editorMixin.js
It never worked reliably in Collectives and we have it in Text these days.
=> chore(cleanup): Remove debugYjs function

.github/workflows/app-upgrade-mysql.yml, .github/workflows/app-upgrade-postgres.yml, .github/workflows/cypress-e2e.yml, .github/workflows/psalm-migrations.yml, CHANGELOG.md, appinfo/info.xml, lib/Command/GenerateSlugs.php, lib/Migration/GenerateSlugs.php
Prevents the slug generation from failing early when the CircleHelper throws an error.
=> fix(slugs): Ignore errors from CircleHelper

appinfo/info.xml, lib/Migration/GenerateSlugs.php, src/router.js
* fix(router): Handle routes without collective slug but with page slug
* fix(migration): Change GenerateSlugs to a live-migration step
The migration requires a newly introduced dependency `symfony/string`,
so it will fail to run within the same PHP process that upgrades the
app from any version before 3.0.0.
* Fixes: #1879
=> Fix slugs migration and opening page slug routes without collective slug

.github/workflows/cypress-e2e.yml, cypress/e2e/pages-links.spec.js, lib/Service/PageService.php
Opening `http://example.org` (instead of `https`) resulted in `ERR_EMPTY_RESPONSE (-324) loading 'http://example.org/'` recently.
=> test(cy): Only test link handling against `https` URLs

lib/Migration/GenerateSlugs.php
=> fix(GenerateSlugs): Stop migration if slugs already got generated

lib/Service/SessionService.php, tests/Integration/features/collectiveSession.feature
Should fix racy situations where update session request comes too late and as a result a new session needs to get created.
=> fix(session): Raise session valid time to 120 seconds

.gitignore, cypress/e2e/page-details.spec.js, cypress/support/navigation.js, src/components/Page/PageActionMenu.vue
Also move "Manage tags" action up in front of copy/move action.
Fixes: #1347
---|---
=> feat(PageActions): Add action to download markdown file

src/components/Page/TagsModal.vue
* Resolves: # none
Found some more icons that weren't outline styled
---|---
B | A
=> Migrate icon from filled to outlined variant

src/components/PageList/Item.vue
This PR replaces the outlined star icon which is placed on a favorite item in the pages' list with a filled variant.
|
=> use filled star icon for fav items in page list

src/mixins/pageMixin.js
No need to mark current page as loading when copying a page or moving another page.
=> fix(pageList): Current page loading only when moving itself

cypress/e2e/collective-offline.js, cypress/support/commands.js, src/components/Collective.vue, src/components/PageSidebar/OfflineContent.vue, src/components/PageSidebar/SharingEntryLink.vue, src/components/PageSidebar/SidebarTabAttachments.vue, src/components/PageSidebar/SidebarTabBacklinks.vue, src/components/PageSidebar/SidebarTabVersions.vue, src/composables/useNetworkState.ts, src/views/CollectiveView.vue
* Handle offline state in all page sidebar tabs
* Add offline state indicator
* Don't send page API requests when offline
* Resolves: #1796
* Resolves: #1961 
Desktop | Mobile | Mobile clicked
--- | --- | ---
Versions tab | Attachments tab | Shares tab
---|--- | ---
Before | Pages request error new | Any other request error new
--- | --- | ---
=> feat: track online/offline state
